-- Create Categories Table
create table public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  slug text not null unique
);

-- Create Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price decimal(10,2) not null,
  image_url text,
  stock integer default 0,
  category_id bigint references public.categories(id)
);

-- Create Orders Table
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text,
  total decimal(10,2) not null,
  status text default 'pending' check (status in ('pending', 'paid', 'shipped', 'cancelled'))
);

-- Create Order Items Table
create table public.order_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_id bigint references public.orders(id),
  product_id bigint references public.products(id),
  quantity integer not null,
  price decimal(10,2) not null
);

-- Insert some initial categories
insert into public.categories (name, slug) values
('Camisas', 'camisas'),
('Pantalones', 'pantalones'),
('Sacos', 'sacos'),
('Accesorios', 'accesorios');

-- Enable Row Level Security (RLS)
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Create policies (Public Read Access for Storefront)
create policy "Public categories are viewable by everyone" on public.categories for select using (true);
create policy "Public products are viewable by everyone" on public.products for select using (true);

-- Policies for Orders (Simple version: anyone can create, only admin/owner can view - for now public create)
create policy "Anyone can create orders" on public.orders for insert with check (true);
create policy "Anyone can create order items" on public.order_items for insert with check (true);
