
-- Ensure Categories Exist
INSERT INTO public.categories (name, slug) VALUES
('Remeras', 'remeras'),
('Camisas', 'camisas'),
('Bermudas', 'bermudas'),
('Camperas', 'camperas'),
('Pantalon Gabardina', 'pantalon-gabardina'),
('Short Baño', 'short-bano')
ON CONFLICT (slug) DO NOTHING;

-- Import Products SQL

INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Gabardina_Cargo_Beige_Talle_40_42_44_46_48_50', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Gabardina_Cargo_Beige_Talle_40_42_44_46_48_50.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Gabardina_Cargo_Gris_Talle_40_42_44_46_48_50', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Gabardina_Cargo_Gris_Talle_40_42_44_46_48_50.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Jeans_Baggy_Talle_M_L_XL_XXL_1', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Jeans_Baggy_Talle_M_L_XL_XXL_1.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Jeans_Baggy_Talle_M_L_XL_XXL_2', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Jeans_Baggy_Talle_M_L_XL_XXL_2.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Jeans_Baggy_Talle_M_L_XL_XXL_3', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Jeans_Baggy_Talle_M_L_XL_XXL_3.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Jeans_Cargo_Talle_M_L_XL_1', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Jeans_Cargo_Talle_M_L_XL_1.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Jeans_Cargo_Talle_M_L_XL_2', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Jeans_Cargo_Talle_M_L_XL_2.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Jeans_Cargo_Talle_M_L_XL_3', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Jeans_Cargo_Talle_M_L_XL_3.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Jeans_Cargo_Talle_M_L_XL_4', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Jeans_Cargo_Talle_M_L_XL_4.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Jeans_Cargo_Talle_M_L_XL_5', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Jeans_Cargo_Talle_M_L_XL_5.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Jeans_Rigida_Con_Roturas_Talle_S_L_XL', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Jeans_Rigida_Con_Roturas_Talle_S_L_XL.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Jeans_Rigida_M_L_XL_XXXL_1', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Jeans_Rigida_M_L_XL_XXXL_1.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Jeans_Rigida_M_L_XL_XXXL_2', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Jeans_Rigida_M_L_XL_XXXL_2.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Jeans_Rigida_M_L_XL_XXXL_3', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Jeans_Rigida_M_L_XL_XXXL_3.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Oversize_Algodon_Aqua_Talle_L_1', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Oversize_Algodon_Aqua_Talle_L_1.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Oversize_Algodon_Negra_Talle_L_1', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Oversize_Algodon_Negra_Talle_L_1.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Oversize_Algodon_Negra_Talle_L_2', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Oversize_Algodon_Negra_Talle_L_2.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Oversize_Algodon_Rustica_Talle_M_XL_1', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Oversize_Algodon_Rustica_Talle_M_XL_1.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Oversize_Algodon_Rustica_Talle_M_XL_2', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Oversize_Algodon_Rustica_Talle_M_XL_2.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Bermudas - Bermuda_Oversize_Algodon_Rustica_Talle_M_XL_3', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'bermudas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Bermudas/Bermuda_Oversize_Algodon_Rustica_Talle_M_XL_3.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Camisas - Camisa_lino_entallada_Crudo', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'camisas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Camisas/Camisa_lino_entallada_Crudo.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Camisas - Camisa_negra_lino_talle_S', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'camisas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Camisas/Camisa_negra_lino_talle_S.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Camperas - Campera_Jeans_Rigida_Negra_Gastada', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'camperas' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Camperas/Campera_Jeans_Rigida_Negra_Gastada.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Pantalon_Gabardina - Pantalon_Gabardina_Cargo_Negro_Talle_42_44_46', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'pantalon-gabardina' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Pantalon_Gabardina/Pantalon_Gabardina_Cargo_Negro_Talle_42_44_46.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Pantalon_Gabardina - Pantalon_Gabardina_Cargo_Verde_Militar_Talle_42', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'pantalon-gabardina' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Pantalon_Gabardina/Pantalon_Gabardina_Cargo_Verde_Militar_Talle_42.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Pantalon_Gabardina - Pantalon_Gabardina_Chino_Beige_Talle_40_42_48_50', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'pantalon-gabardina' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Pantalon_Gabardina/Pantalon_Gabardina_Chino_Beige_Talle_40_42_48_50.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Pantalon_Gabardina - Pantalon_Gabardina_Chino_Manteca_Elastizado_Talle_46', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'pantalon-gabardina' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Pantalon_Gabardina/Pantalon_Gabardina_Chino_Manteca_Elastizado_Talle_46.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Pantalon_Gabardina - Pantalon_Gabardina_Chino_Tostado_Elastizado_Talle_40_42_44_46_1', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'pantalon-gabardina' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Pantalon_Gabardina/Pantalon_Gabardina_Chino_Tostado_Elastizado_Talle_40_42_44_46_1.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Pantalon_Gabardina - Pantalon_Gabardina_Chino_Tostado_Elastizado_Talle_40_42_44_46_2', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'pantalon-gabardina' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Pantalon_Gabardina/Pantalon_Gabardina_Chino_Tostado_Elastizado_Talle_40_42_44_46_2.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Algodon_Lycra_Blanca', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Algodon_Lycra_Blanca.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Algodon_Lycra_CuelloV_Blanca', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Algodon_Lycra_CuelloV_Blanca.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Boxi_Crema_Talle_L_1', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Boxi_Crema_Talle_L_1.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Boxi_Crema_Talle_L_2', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Boxi_Crema_Talle_L_2.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Boxy_Blanca_Talle_L_1', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Boxy_Blanca_Talle_L_1.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Boxy_Blanca_Talle_L_2', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Boxy_Blanca_Talle_L_2.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Boxy_Crema_Talle_L_1', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Boxy_Crema_Talle_L_1.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Boxy_Crema_Talle_L_2', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Boxy_Crema_Talle_L_2.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Boxy_Gris_Talle_M_1', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Boxy_Gris_Talle_M_1.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Boxy_Gris_Talle_M_2', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Boxy_Gris_Talle_M_2.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Limited_Edition_Talle_L', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Limited_Edition_Talle_L.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Linkin_Park_Negra_Talle_M', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Linkin_Park_Negra_Talle_M.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Negra_Algodon_Lycra', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Negra_Algodon_Lycra.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Oversize_Estampa_Espalda_Better_Days_Ahead_Negra_Talle_Xl', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Oversize_Estampa_Espalda_Better_Days_Ahead_Negra_Talle_Xl.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Oversize_Estampa_Espalda_Obsession_Negra_Talle_M', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Oversize_Estampa_Espalda_Obsession_Negra_Talle_M.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Oversize_Estampa_Espalda_Try Some_Thing_New_Nega_Talle_L', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Oversize_Estampa_Espalda_Try%20Some_Thing_New_Nega_Talle_L.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Oversize_Estampa_Espalda_Young_Wild_Free_Blanca_Talla_L', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Oversize_Estampa_Espalda_Young_Wild_Free_Blanca_Talla_L.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Oversize_Estampada_Negra', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Oversize_Estampada_Negra.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Oversize_Estanpa_Espalda_Negra_Talle_M', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Oversize_Estanpa_Espalda_Negra_Talle_M.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Oversize_FreeYourMind_Blanca', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Oversize_FreeYourMind_Blanca.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Oversize_Linkin_Park_Talle_Xl_Negra_Frente', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Oversize_Linkin_Park_Talle_Xl_Negra_Frente.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Oversize_Linkin_Park_Talle_Xl_Negra', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Oversize_Linkin_Park_Talle_Xl_Negra.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Oversize_Negra_Estampa_Espalda_Stolen', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Oversize_Negra_Estampa_Espalda_Stolen.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Remeras - Remera_Oversize_Negra_Talle_XL', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'remeras' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Remeras/Remera_Oversize_Negra_Talle_XL.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Short_Bano - Short_Bano_Azul_Talle_XXL', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'short-bano' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Short_Bano/Short_Bano_Azul_Talle_XXL.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Short_Bano - Short_Bano_Beige_Talle_M_L_XXL_1', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'short-bano' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Short_Bano/Short_Bano_Beige_Talle_M_L_XXL_1.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Short_Bano - Short_Bano_Beige_Talle_M_L_XXL_2', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'short-bano' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Short_Bano/Short_Bano_Beige_Talle_M_L_XXL_2.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Short_Bano - Short_Bano_Celeste_Talle_XXL', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'short-bano' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Short_Bano/Short_Bano_Celeste_Talle_XXL.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Short_Bano - Short_Bano_Gris_Talle_M', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'short-bano' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Short_Bano/Short_Bano_Gris_Talle_M.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Short_Bano - Short_Bano_Negra_Talle_L', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'short-bano' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Short_Bano/Short_Bano_Negra_Talle_L.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Short_Bano - Short_Bano_Roja_Talle_M', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'short-bano' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Short_Bano/Short_Bano_Roja_Talle_M.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Short_Bano - Short_Bano_Rosa_Talle_S_L', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'short-bano' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Short_Bano/Short_Bano_Rosa_Talle_S_L.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Short_Bano - Short_Bano_Verde_Loro_Talle_XL_1', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'short-bano' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Short_Bano/Short_Bano_Verde_Loro_Talle_XL_1.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Short_Bano - Short_Bano_Verde_Loro_Talle_XL_2', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'short-bano' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Short_Bano/Short_Bano_Verde_Loro_Talle_XL_2.jpg');
INSERT INTO public.products (name, description, price, stock, category_id, image_url) VALUES ('Short_Bano - Short_Bano_Verde_Talle_XL', 'Imported from storage', 0, 10, (SELECT id FROM public.categories WHERE slug = 'short-bano' LIMIT 1), 'https://tpitmedayuzfjooxyzgm.supabase.co/storage/v1/object/public/products/Short_Bano/Short_Bano_Verde_Talle_XL.jpg');
